version: '2'
volumes:
  settings:
services:
  kiosk:
    restart: always
    build: ./kiosk
    privileged: true
    ports:
      - 5011:5011
      - 35174:35174
    volumes:
      - 'settings:/data'
  scheduler:
    restart: always
    build: ./scheduler
    privileged: true
  wifi-connect:
    build: ./wifi-connect
    restart: always
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.firmware: '1'
  fbcp:
    build: ./fbcp
    restart: on-failure
    privileged: true
  browsercontrol:
    build: ./browsercontrol
    restart: always
    privileged: true
    ports:
      - 8080:80
